### ISSUE TITLE
question about using LDM or DM

### ISSUE THREAD

**Issue by wwbwang** [IceClear/StableSR#29]
Hello, I found that you splited the larger image into several overlapping smaller patches and processing each one individually. My question is, since the larger image is splited, why still train and sample in latent space? Why not train and sample in spatial pixel space directly and using DM? 
In fact, I found many SR methods based on diffusion model don't split images into small patch and train on them, which is different from CNN and GAN methods previously. They would rather put a larger image into "tight" latent space to compress it. It confused me a lot, hope you can help me.
Thanks in advance!

**Comment by IceClear** [comment]
Because our model is based on diffusion prior, and this part is fixed. The performance of SD drops significantly on large size.
Training from scratch in pixel space requires huge computation resources. Even LDM requires about 2.6M steps with 256 batch size and SR3 in pixel space should require much more.
Avoiding the huge cost of training from scratch is actually the main motivation in our paper.

**Comment by wwbwang** [comment]
Thanks for your quick response, helps a lot
