### ISSUE TITLE
Linked Colab Demo doesn't work.

### ISSUE THREAD

**Issue by jarredou** [IceClear/StableSR#6]
This project looks really promising but the given demo doesn't work and make Colab fullcrash. Don't know if Colab has problems now but after trying to run the install of your Colab demo, I can't even disconnect/reconnect after the crash, I can't even delete runtime and must wait hours for a server-side reset of my account... :(

**Comment by Ivan29B** [comment]
Provide information about your problem that you have encountered. As the presence of the problem itself, with a description here we will help to solve it for you.

**Comment by Ivan29B** [comment]
Provide detailed information (Console Report) about your problem you encountered. As having the problem itself, with a description here we will help you solve it, and improve the stability of future releases.

**Comment by IceClear** [comment]
Hi~
Thanks for your interest.
Would you mind trying another way to install and activate conda env following this [link](https://colab.research.google.com/drive/1BNtoPPRuJwNDvqfwDOOmD9XJyF05Zh4m?usp=sharing#scrollTo=kpIhX5d5R6cP)?
We both use conda env and I guess it may be the problem of using the conda env but I am not very familiar with Colab so I do not have solutions now.
I do not have a pro account and I have run out of my quota today.
Sry that I cannot help now.
I may try to figure out the reason after I have free quota again.

**Comment by IceClear** [comment]
> I'm only getting a kind of "Your session crashed, restarting..." notifications during the installation, and then Colab is stucked on "reconnecting", and never reconnects.

Hi. I now meet the same error as you :(
It seems like the issue of condacolab, see [here](https://github.com/conda-incubator/condacolab/issues/52).
I am still working to figure out the solution.

**Comment by IceClear** [comment]
Hi, guys.
Thanks all your kind help, especially thank @francqz31 for devoting time on this.
I have conducted a detailed test and fixed most of the errors.
Colab is a little bit strange since the packages in the env file should be installed after creating the environment, but it seems I have to reinstall again on the colab. I am not familiar with it so I do not know the reason.
Anyway, I think now at least you should be able to run if you have enough RAM, I am stuck on the System RAM since the basic 13G seems not enough for StableSR to run :(

BTW, I have to say, the price to run Stable diffusion-based models like StableSR or IF can be very high. 16G GPU is just enough for a very tiny run, e.g., generating 512x512 images. Also, there is an additional requirement for system RAM. I think my next focus has to turn to how to save the huge cost of diffusion models if possible ...

**Comment by ARTUROSING** [comment]
> @IceClear Здравствуйте, я видел блокнот, в нем было много ошибок, я исправил ошибки, за исключением Cuda нехватки памяти, я думаю, что ему нужен Colab pro + не только pro, я попробовал его на Kaggle с p100, и он все равно выдал мне «Ваш ноутбук попробовал выделять слишком много памяти и не может быть восстановлено». В любом случае, вот полностью исправленная версия Colab, если вы хотите сохранить ее в своей учетной записи и изменить ссылку на Colab в файле readme, не стесняйтесь делать это. https://colab.research.google.com/drive/1LcoDjd9pTp3BpS1upPFbmMe4xC0kkzQu?usp=sharing

You reported that you made some fixes to the google colab StableSR laptop, but trying to click on the link you provided requires permission or access to your laptop.

Could you please grant access, for study purposes.
Thank you for your consideration.

**Comment by IceClear** [comment]
> @ARTUROSING sorry my account got disabled for a bit That's why , use this instead https://colab.research.google.com/drive/11SE2_oDvbYtcuHDbaLAxsKk_o3flsO1T?usp=sharing it is basically the same , the author took from the my modified version and added it there :) . any ways it wont work since it needs big ram unless you have google colab pro + , even on pro + it might not work , it needs like "A100 80gb" I think. you are welcome

Hi, @francqz31 and @ARTUROSING . May I know what is the problem of the latest colab I published? From my side, it seems like not enough system ram rather than gpu memory. I tested on my local computer and now the gpu requirement should not be that high, i.e., 10G should be enough for testing on 4x SR on 128x128.
Thanks for your help.

**Comment by IceClear** [comment]
> > @ARTUROSING sorry my account got disabled for a bit That's why , use this instead https://colab.research.google.com/drive/11SE2_oDvbYtcuHDbaLAxsKk_o3flsO1T?usp=sharing it is basically the same , the author took from the my modified version and added it there :) . any ways it wont work since it needs big ram unless you have google colab pro + , even on pro + it might not work , it needs like "A100 80gb" I think. you are welcome
> 
> Hi, @francqz31 and @ARTUROSING . May I know what is the problem of the latest colab I published? From my side, it seems like not enough system ram rather than gpu memory. I tested on my local computer and now the gpu requirement should not be that high, i.e., 10G should be enough for testing on 4x SR on 128x128. Thanks for your help.

I have successfully run the Colab demo using the Colab Pro I just bought : )
To run the demo you may have to use the High-RAM runtime which is available for Pro and Pro+.
For GPU memory, 16G is enough.
Thank @francqz31 for providing great help on this demo.
And also thank others for the patience of the demo.
